In [11]:
import numpy as np

# Mejora de la legibilidad numérica
np.set_printoptions(precision=3, suppress=True)

# -----------------------------
# Paso 0 – Creamos dos matrices de activaciones de ejemplo
# -----------------------------
np.random.seed(42)
n, p = 33, 45         # 8 ejemplos, 4 neuronas
X = np.random.randn(n, p)
X

array([[ 0.497, -0.138,  0.648, ..., -0.116, -0.301, -1.479],
       [-0.72 , -0.461,  1.057, ...,  0.329, -0.53 ,  0.513],
       [ 0.097,  0.969, -0.702, ..., -1.062,  0.474, -0.919],
       ...,
       [-1.17 , -1.802,  0.541, ...,  2.013,  0.137, -0.365],
       [ 0.185, -1.347, -0.972, ...,  1.607,  0.491,  0.735],
       [ 0.663,  1.173,  0.181, ...,  1.727, -0.4  ,  0.225]])

In [13]:

# factores de escala: 0.9, 0.6, 0.3, 0.1 para las cuatro primeras columnas,
# 1.0 para las 41 restantes
scales = [0.9, 0.6, 0.3, 0.1] + [1.0]*(p - 4)
transform = np.diag(scales)        # (45 × 45)

np.set_printoptions(precision=3, suppress=True)
Y = X @ transform + 0.5 * np.random.randn(n, p)   # (33 × 45)
print(Y)

[[ 0.913 -0.792 -0.686 ...  0.656 -0.546 -2.038]
 [-0.577 -1.161  0.479 ...  0.476 -1.208  0.746]
 [ 0.07  -0.226  0.372 ... -1.438  0.26  -0.345]
 ...
 [-1.203 -0.129  0.975 ...  1.679  0.283 -0.459]
 [-0.953 -1.869 -0.595 ...  1.51   0.459  0.781]
 [ 0.723  0.646  0.162 ...  1.442 -1.31   0.36 ]]


In [14]:

# -----------------------------
# Paso 1 – Centramos cada matriz
# -----------------------------
Xc = X - X.mean(axis=0)
Yc = Y - Y.mean(axis=0)
Yc

array([[ 0.729, -0.524, -0.71 , ...,  0.48 , -0.535, -2.231],
       [-0.761, -0.892,  0.455, ...,  0.3  , -1.198,  0.554],
       [-0.114,  0.042,  0.348, ..., -1.614,  0.271, -0.538],
       ...,
       [-1.387,  0.139,  0.952, ...,  1.504,  0.293, -0.652],
       [-1.137, -1.6  , -0.618, ...,  1.334,  0.469,  0.588],
       [ 0.539,  0.914,  0.138, ...,  1.266, -1.299,  0.167]])

In [40]:

# -----------------------------
# Paso 2 – Descomposición PCA vía SVD y selección de las k bases principales
# -----------------------------
k = 25
Ux, Sx, Vhx = np.linalg.svd(Xc, full_matrices=False)   # Vhx tiene forma (p, p)
Uy, Sy, Vhy = np.linalg.svd(Yc, full_matrices=False)

V_k = Vhx.T[:, :k]     # columnas ≡ vectores propios de X (p × k)
U_k = Vhy.T[:, :k]     # columnas ≡ vectores propios de Y (p × k)


In [41]:
print(Ux); print("");print(Sx); print("");print(Vhx)

[[ 0.075 -0.159  0.22  ...  0.217  0.099  0.174]
 [-0.098  0.128  0.177 ...  0.254 -0.056  0.174]
 [-0.091  0.145 -0.194 ...  0.219  0.013  0.174]
 ...
 [ 0.359 -0.018  0.027 ... -0.225 -0.037  0.174]
 [-0.061  0.066  0.299 ... -0.233  0.274  0.174]
 [-0.012  0.076 -0.152 ... -0.079 -0.174  0.174]]

[12.201 11.109 10.001  9.929  9.702  9.2    8.591  8.46   8.038  7.55
  7.237  6.946  6.829  6.385  6.221  5.762  5.424  5.173  4.836  4.803
  4.539  4.284  3.98   3.728  3.292  3.043  2.928  2.698  2.283  1.936
  1.528  1.267  0.   ]

[[-0.111 -0.04   0.03  ...  0.109  0.081 -0.082]
 [-0.103  0.152  0.057 ...  0.001 -0.024 -0.051]
 [ 0.031 -0.186  0.151 ...  0.018  0.157 -0.09 ]
 ...
 [ 0.192 -0.117 -0.272 ... -0.215 -0.313  0.022]
 [ 0.176  0.256 -0.021 ...  0.316  0.079  0.104]
 [-0.018  0.043 -0.002 ...  0.157 -0.154 -0.049]]


In [42]:
print(V_k,"\n------\n" ,U_k, "\n------\n", V_k.T )

[[-0.111 -0.103  0.031 ... -0.233 -0.163 -0.174]
 [-0.04   0.152 -0.186 ...  0.097 -0.051  0.044]
 [ 0.03   0.057  0.151 ... -0.296 -0.002 -0.185]
 ...
 [ 0.109  0.001  0.018 ... -0.234 -0.187  0.153]
 [ 0.081 -0.024  0.157 ...  0.026  0.024  0.246]
 [-0.082 -0.051 -0.09  ... -0.06   0.17   0.013]] 
------
 [[-0.08   0.059  0.023 ...  0.12  -0.357 -0.198]
 [ 0.048 -0.018  0.142 ...  0.111  0.412 -0.037]
 [ 0.05   0.02   0.082 ... -0.031 -0.11   0.001]
 ...
 [ 0.108 -0.037  0.04  ...  0.296 -0.011  0.123]
 [ 0.111  0.172  0.043 ...  0.015  0.068  0.123]
 [-0.09  -0.134  0.209 ...  0.05   0.005 -0.082]] 
------
 [[-0.111 -0.04   0.03  ...  0.109  0.081 -0.082]
 [-0.103  0.152  0.057 ...  0.001 -0.024 -0.051]
 [ 0.031 -0.186  0.151 ...  0.018  0.157 -0.09 ]
 ...
 [-0.233  0.097 -0.296 ... -0.234  0.026 -0.06 ]
 [-0.163 -0.051 -0.002 ... -0.187  0.024  0.17 ]
 [-0.174  0.044 -0.185 ...  0.153  0.246  0.013]]


In [43]:

# -----------------------------
# Paso 3 – Producto entre subespacios
# -----------------------------
M = V_k.T @ U_k        # (k × k)
M

array([[ 0.773,  0.452,  0.17 , -0.05 ,  0.217,  0.207, -0.061,  0.06 ,
        -0.009,  0.058, -0.036,  0.036, -0.032, -0.023, -0.013, -0.091,
        -0.058, -0.011, -0.006, -0.013, -0.024,  0.02 , -0.003,  0.07 ,
        -0.013],
       [ 0.493, -0.783,  0.005, -0.1  , -0.082, -0.093, -0.092, -0.061,
         0.134, -0.06 ,  0.094,  0.02 , -0.109,  0.005, -0.029, -0.081,
         0.096,  0.09 , -0.096,  0.07 ,  0.012,  0.034, -0.001,  0.072,
         0.022],
       [ 0.183,  0.119, -0.752,  0.242, -0.031, -0.266,  0.054,  0.009,
        -0.149,  0.025,  0.031,  0.124, -0.194, -0.16 ,  0.159,  0.035,
         0.025,  0.01 , -0.038, -0.028,  0.046,  0.108,  0.001, -0.083,
         0.143],
       [-0.   ,  0.16 ,  0.084, -0.543,  0.261, -0.592, -0.016,  0.003,
         0.18 , -0.007,  0.05 ,  0.134,  0.085, -0.102, -0.048,  0.193,
         0.076,  0.176,  0.008,  0.109,  0.115,  0.033, -0.038, -0.11 ,
        -0.039],
       [-0.052,  0.107, -0.358, -0.501, -0.233,  0.306, -0.307,  0.2

In [44]:

# -----------------------------
# Paso 4 – Norma de Frobenius y métrica SubspaceSim
# -----------------------------
fro2 = np.linalg.norm(M, ord='fro') ** 2
subspace_sim = fro2 / k

# -----------------------------
# Mostramos resultados intermedios y finales
# -----------------------------
print("X centrada:\n", Xc)
print("\nY centrada:\n", Yc)

print("\nV_k (tarea 1, primeras k bases):\n", V_k)
print("\nU_k (tarea 2, primeras k bases):\n", U_k)

print("\nM = V_k.T @ U_k:\n", M)
print(f"\n||M||_F^2 = {fro2:.4f}")
print(f"SubspaceSim_k(X, Y) = {subspace_sim:.4f}")


X centrada:
 [[ 0.357  0.264  0.684 ... -0.406 -0.388 -1.671]
 [-0.86  -0.059  1.094 ...  0.039 -0.616  0.32 ]
 [-0.043  1.371 -0.665 ... -1.352  0.387 -1.112]
 ...
 [-1.31  -1.4    0.578 ...  1.723  0.05  -0.558]
 [ 0.045 -0.945 -0.935 ...  1.317  0.404  0.542]
 [ 0.523  1.575  0.218 ...  1.437 -0.486  0.032]]

Y centrada:
 [[ 0.729 -0.524 -0.71  ...  0.48  -0.535 -2.231]
 [-0.761 -0.892  0.455 ...  0.3   -1.198  0.554]
 [-0.114  0.042  0.348 ... -1.614  0.271 -0.538]
 ...
 [-1.387  0.139  0.952 ...  1.504  0.293 -0.652]
 [-1.137 -1.6   -0.618 ...  1.334  0.469  0.588]
 [ 0.539  0.914  0.138 ...  1.266 -1.299  0.167]]

V_k (tarea 1, primeras k bases):
 [[-0.111 -0.103  0.031 ... -0.233 -0.163 -0.174]
 [-0.04   0.152 -0.186 ...  0.097 -0.051  0.044]
 [ 0.03   0.057  0.151 ... -0.296 -0.002 -0.185]
 ...
 [ 0.109  0.001  0.018 ... -0.234 -0.187  0.153]
 [ 0.081 -0.024  0.157 ...  0.026  0.024  0.246]
 [-0.082 -0.051 -0.09  ... -0.06   0.17   0.013]]

U_k (tarea 2, primeras k bases):
 [[-