In [59]:
import numpy as np

# Mejora de la legibilidad numérica
np.set_printoptions(precision=3, suppress=True)

# -----------------------------
# Paso 0 – Creamos dos matrices de activaciones de ejemplo
# -----------------------------
np.random.seed(42)
n, p = 8, 4         # 8 ejemplos, 4 neuronas
X = np.random.randn(n, p)
X

array([[ 0.497, -0.138,  0.648,  1.523],
       [-0.234, -0.234,  1.579,  0.767],
       [-0.469,  0.543, -0.463, -0.466],
       [ 0.242, -1.913, -1.725, -0.562],
       [-1.013,  0.314, -0.908, -1.412],
       [ 1.466, -0.226,  0.068, -1.425],
       [-0.544,  0.111, -1.151,  0.376],
       [-0.601, -0.292, -0.602,  1.852]])

In [60]:

# Para Y creamos algo relacionado pero no idéntico
transform = np.array([[0.9, 0.0, 0.0, 0.0],
                      [0.0, 0.6, 0.0, 0.0],
                      [0.0, 0.0, 0.3, 0.0],
                      [0.0, 0.0, 0.0, 0.1]])
Y = X @ transform + 0.5 * np.random.randn(n, p)
Y

array([[ 0.44 , -0.612,  0.606, -0.458],
       [-0.106, -1.12 , -0.19 ,  0.175],
       [-0.053,  0.411, -0.197, -0.197],
       [-0.521, -1.508, -0.748,  0.472],
       [-0.74 , -0.693, -0.11 , -0.334],
       [ 0.981,  0.17 ,  0.536,  0.323],
       [-0.91 , -0.088, -0.18 ,  0.525],
       [-0.78 , -0.268, -0.734, -0.413]])

In [61]:

# -----------------------------
# Paso 1 – Centramos cada matriz
# -----------------------------
Xc = X - X.mean(axis=0)
Yc = Y - Y.mean(axis=0)
Yc

array([[ 0.651, -0.148,  0.733, -0.47 ],
       [ 0.105, -0.657, -0.063,  0.163],
       [ 0.158,  0.875, -0.07 , -0.209],
       [-0.31 , -1.044, -0.621,  0.461],
       [-0.529, -0.23 ,  0.017, -0.346],
       [ 1.192,  0.634,  0.663,  0.311],
       [-0.698,  0.375, -0.052,  0.514],
       [-0.569,  0.196, -0.607, -0.425]])

In [62]:

# -----------------------------
# Paso 2 – Descomposición PCA vía SVD y selección de las k bases principales
# -----------------------------
k = 4
Ux, Sx, Vhx = np.linalg.svd(Xc, full_matrices=False)   # Vhx tiene forma (p, p)
Uy, Sy, Vhy = np.linalg.svd(Yc, full_matrices=False)

V_k = Vhx.T[:, :k]     # columnas ≡ vectores propios de X (p × k)
U_k = Vhy.T[:, :k]     # columnas ≡ vectores propios de Y (p × k)


In [70]:
print(Ux); print("");print(Sx); print("");print(Vhx)

[[-0.472  0.129  0.201 -0.278]
 [-0.44   0.363 -0.082  0.656]
 [ 0.121  0.029 -0.394 -0.169]
 [ 0.409 -0.312  0.652  0.363]
 [ 0.406 -0.045 -0.526  0.263]
 [ 0.31   0.644  0.258 -0.381]
 [ 0.039 -0.336 -0.162 -0.312]
 [-0.373 -0.473  0.054 -0.143]]

[3.62  2.693 2.309 1.145]

[[ 0.043 -0.104 -0.533 -0.838]
 [ 0.5    0.167  0.719 -0.452]
 [ 0.618 -0.748 -0.127  0.206]
 [-0.605 -0.634  0.427 -0.224]]


In [63]:
print(V_k,"\n------\n" ,U_k, "\n------\n", V_k.T )

[[ 0.043  0.5    0.618 -0.605]
 [-0.104  0.167 -0.748 -0.634]
 [-0.533  0.719 -0.127  0.427]
 [-0.838 -0.452  0.206 -0.224]] 
------
 [[-0.699  0.462 -0.063 -0.543]
 [-0.489 -0.846 -0.202 -0.066]
 [-0.517  0.201  0.141  0.82 ]
 [ 0.072  0.176 -0.967  0.169]] 
------
 [[ 0.043 -0.104 -0.533 -0.838]
 [ 0.5    0.167  0.719 -0.452]
 [ 0.618 -0.748 -0.127  0.206]
 [-0.605 -0.634  0.427 -0.224]]


In [64]:

# -----------------------------
# Paso 3 – Producto entre subespacios
# -----------------------------
M = V_k.T @ U_k        # (k × k)
M

array([[ 0.236, -0.146,  0.754, -0.596],
       [-0.836,  0.154,  0.474,  0.231],
       [ 0.014,  0.929, -0.105, -0.355],
       [ 0.496,  0.304,  0.443,  0.682]])

In [65]:

# -----------------------------
# Paso 4 – Norma de Frobenius y métrica SubspaceSim
# -----------------------------
fro2 = np.linalg.norm(M, ord='fro') ** 2
subspace_sim = fro2 / k

# -----------------------------
# Mostramos resultados intermedios y finales
# -----------------------------
print("X centrada:\n", Xc)
print("\nY centrada:\n", Yc)

print("\nV_k (tarea 1, primeras k bases):\n", V_k)
print("\nU_k (tarea 2, primeras k bases):\n", U_k)

print("\nM = V_k.T @ U_k:\n", M)
print(f"\n||M||_F^2 = {fro2:.4f}")
print(f"SubspaceSim_k(X, Y) = {subspace_sim:.4f}")


X centrada:
 [[ 0.579  0.091  0.967  1.441]
 [-0.152 -0.005  1.899  0.686]
 [-0.387  0.772 -0.144 -0.547]
 [ 0.324 -1.684 -1.406 -0.644]
 [-0.931  0.544 -0.589 -1.494]
 [ 1.548  0.004  0.387 -1.506]
 [-0.462  0.34  -0.832  0.294]
 [-0.518 -0.062 -0.282  1.771]]

Y centrada:
 [[ 0.651 -0.148  0.733 -0.47 ]
 [ 0.105 -0.657 -0.063  0.163]
 [ 0.158  0.875 -0.07  -0.209]
 [-0.31  -1.044 -0.621  0.461]
 [-0.529 -0.23   0.017 -0.346]
 [ 1.192  0.634  0.663  0.311]
 [-0.698  0.375 -0.052  0.514]
 [-0.569  0.196 -0.607 -0.425]]

V_k (tarea 1, primeras k bases):
 [[ 0.043  0.5    0.618 -0.605]
 [-0.104  0.167 -0.748 -0.634]
 [-0.533  0.719 -0.127  0.427]
 [-0.838 -0.452  0.206 -0.224]]

U_k (tarea 2, primeras k bases):
 [[-0.699  0.462 -0.063 -0.543]
 [-0.489 -0.846 -0.202 -0.066]
 [-0.517  0.201  0.141  0.82 ]
 [ 0.072  0.176 -0.967  0.169]]

M = V_k.T @ U_k:
 [[ 0.236 -0.146  0.754 -0.596]
 [-0.836  0.154  0.474  0.231]
 [ 0.014  0.929 -0.105 -0.355]
 [ 0.496  0.304  0.443  0.682]]

||M||_F^2 